[HIPPEROS] Configuration and minimal syscall implementation
hipperos/newlib pull request #1
Opened 2017-01-24 11:28 UTC by odesenfans

Added support for the `*-*-hipperos*` triplets in newlib. This configuration
builds `newlib` for the HIPPEROS RTOS.

Implemented minimal versions of all required (reentrant) syscalls.
The implementations of `_getpid_r`, `_exit` and `_printf_r` are
functional.

2017-01-24 15:12 UTC, VladimirSvoboda requested changes
Some small changes. Try to use the same version of `auto*` as them.

2017-01-24 15:12 UTC, VladimirSvoboda commented on newlib/configure.host
> +  *-*-hipperos*)
> THIS TABLE IS ALPHA SORTED. KEEP IT THAT WAY.

2017-01-24 15:12 UTC, VladimirSvoboda commented on newlib/libc/sys/configure.in
> +    hipperos) AC_CONFIG_SUBDIRS(hipperos) ;;
Should start with a TAB and alpha sorted.

2017-01-24 15:12 UTC, VladimirSvoboda commented on newlib/libc/sys/hipperos/crt0.c
> +#include <fcntl.h>
Why?

2017-01-24 15:12 UTC, VladimirSvoboda commented on newlib/libc/sys/hipperos/syscalls.c
> +#include <reent.h>
I guess that we will have to add license stuff.

2017-01-24 15:12 UTC, VladimirSvoboda commented on newlib/libc/sys/hipperos/syscalls.c
> +void* _sbrk_r(struct _reent* r, ptrdiff_t incr)
I think we should try to not rely on this as this is deprecated.

2017-01-24 15:12 UTC, VladimirSvoboda commented on newlib/libc/sys/hipperos/syscalls.c
> +int _getpid_r(struct _reent* r)
Move the implemented functions to their own files and keep the "unimplemented.c" file as we do usually.

2017-01-24 15:12 UTC, VladimirSvoboda commented on newlib/libc/sys/hipperos/syscalls.c
> +        abort();
What does abort do?

2017-01-24 15:20 UTC, odesenfans commented on newlib/configure.host
> +  *-*-hipperos*)
Oops thought I fixed that. My bad.

2017-01-24 15:21 UTC, odesenfans commented on newlib/libc/sys/hipperos/syscalls.c
> +#include <reent.h>
Yes, I don't know what yet.

2017-01-24 15:23 UTC, odesenfans commented on newlib/libc/sys/hipperos/syscalls.c
> +void* _sbrk_r(struct _reent* r, ptrdiff_t incr)
Yup. It's required by their implementation of `malloc` so the clean fix is to provide our implementation of `malloc`.

2017-01-24 15:23 UTC, odesenfans commented on newlib/libc/sys/hipperos/syscalls.c
> +        abort();
Calls `exit(EXIT_FAILURE)`.

2017-01-24 15:33 UTC, odesenfans commented on newlib/configure.host
> +  *-*-hipperos*)
Fixed in 2b9590ca6fbd25e8e78aad87627eae115f863b6d.

2017-01-24 15:33 UTC, odesenfans commented on newlib/libc/sys/configure.in
> +    hipperos) AC_CONFIG_SUBDIRS(hipperos) ;;
2b9590ca6fbd25e8e78aad87627eae115f863b6d

2017-01-24 15:33 UTC, odesenfans commented on newlib/libc/sys/hipperos/crt0.c
> +#include <fcntl.h>
Useless. Fixed in 2b9590ca6fbd25e8e78aad87627eae115f863b6d

2017-01-24 15:33 UTC, odesenfans commented on newlib/libc/sys/hipperos/syscalls.c
> +int _getpid_r(struct _reent* r)
Will do that in future revisions.

2017-01-24 15:49 UTC, odesenfans commented on newlib/libc/sys/hipperos/syscalls.c
> +        abort();
The actual implementation is:

```c
_VOID
_DEFUN_VOID (abort)
{
#ifdef ABORT_MESSAGE
  write (2, "Abort called\n", sizeof ("Abort called\n")-1);
#endif

  while (1)
    {
      raise (SIGABRT);
      _exit (1);
    }
}
```

2017-01-25 10:10 UTC, VladimirSvoboda commented on newlib/libc/sys/hipperos/configure
> +# Generated by GNU Autoconf 2.64 for newlib 2.5.0.
Use `autoconf` 2.68 here too (this is what rtems and phoenix do).

2017-01-31 12:50 UTC, paul-rodriguez approved these changes
I like turtles

2017-01-31 12:50 UTC, paul-rodriguez commented on newlib/libc/sys/hipperos/syscalls.c
> +char** environ = __env;
What's the point of these two lines?

2017-01-31 12:55 UTC, odesenfans commented on newlib/libc/sys/hipperos/syscalls.c
> +char** environ = __env;
Those two are the representation of environment variable and must be declared here.

2017-02-04 12:51 UTC, apaolillo commented
How often will we rebase our work on the bare newlib-cygwin repo?

2017-02-04 12:51 UTC, apaolillo approved these changes
Looks ok to me

2017-02-07 09:46 UTC, odesenfans commented
@apaolillo I'd say for each major release, about once a year.

2017-02-14 11:10 UTC, VladimirSvoboda approved these changes

2017-06-15 08:12 UTC, merged